name: eras3r native build
on: [push]
jobs:
    build:
      name: native ${{ matrix.os }} build
      runs-on: ${{ matrix.os }}
      defaults:
        run:
          working-directory: ./eras3r
      strategy:
        matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - uses: graalvm/setup-graalvm@v1
          with:
            version: 'latest'
            java-version: '17'
            components: 'native-image'
            github-token: ${{ secrets.GITHUB_TOKEN }}
            native-image-job-reports: 'true'
        - name: environment check
          run: |
            echo "GRAALVM_HOME: $GRAALVM_HOME"
            echo "JAVA_HOME: $JAVA_HOME"
            java --version
        - name: maven build
          run: mvn package
        - name: native build
          run: native-image -jar target/eras3r.jar
        - name: upload unix binaries
          if: ${{matrix.os != 'windows-latest'}}
          uses: actions/upload-artifact@v3
          with:
            name: eras3r-${{ matrix.os }}
            path: eras3r/target/eras3r-runner
            if-no-files-found: error
        - name: upload windows binary
          if: ${{matrix.os == 'windows-latest'}}
          uses: actions/upload-artifact@v3
          with:
            name: eras3r-${{ matrix.os }}
            path: eras3r/target/eras3r-runner.exe
            if-no-files-found: error
